#!/bin/bash

system_type=$(uname -s)

#brew
setup_brew() {
	#install brew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
		ehco "Installing homebrew"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi

	if [[ -f "$HOME"/.Brewfile ]]; then
		echo "Updating homebrew bundle"
		brew bundle -g -v
	fi
}

#iTerm2
setup_iterm() {
	#possibly add something here to ensure iTerm2 is installed using Homebrew
	#cask like in the previous example

	if [[ -d "$HOME/.iterm2" ]]; then
    	echo "Setting iTerm preference folder"
    	defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  	fi
}

#submodules
setup_submodules() {
	echo "Init submodules"
	yadm submodule update --recursive --init
	ln -s -f .tmux/.tmux.conf
	if [[ ! -f "$HOME"/.tmux.conf.local ]]; then
		cp .tmux/.tmux.conf.local "$HOME"/.tmux.conf.local
	fi
}

if [[ "$system_type" = "Darwin" ]]; then
	setup_submodules
	setup_brew
	setup_iterm
fi
