#!/bin/bash

system_type=$(uname -s)

#brew

if [[ "$system_type" = "Darwin" ]]; then
#install brew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
		ehco "Installing homebrew"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	if [[ -f "$HOME"/.Brewfile ]]; then
		echo "Updating homebrew bundle"
		brew bundle -g -v
	fi

fi

#iTerm2
if [ "$system_type" = "Darwin" ]; then
#possibly add something here to ensure iTerm2 is installed using Homebrew
#cask like in the previous example

	if [[ -d "$HOME/.iterm2" ]]; then
    	echo "Setting iTerm preference folder"
    	defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  	fi

fi
